package com.acrovix.admin.entity;

public enum EmailType {
    QUOTATION,
    INVOICE,
    PAYMENT_RECEIPT,
    CRM_LEAD,
    FOLLOW_UP,
    LOGIN_SECURITY,
    WELCOME,
    ENQUIRY,
    ENQUIRY_ASSIGNMENT,
    CRM_LEAD_ASSIGNMENT,
    FOLLOW_UP_DUE,
    FOLLOW_UP_OVERDUE,
    QUOTATION_RESPONSE,
    PO_NOTIFICATION,
    INVOICE_NOTIFICATION,
    INVOICE_OVERDUE,
    PAYMENT_NOTIFICATION,
    GENERAL
}
