package com.acrovix.admin.entity;

public enum NotificationType {
    ENQUIRY_ASSIGNED,
    QUOTATION_SENT,
    QUOTATION_RESPONDED,
    NEW_LEAD_CREATED,
    LEAD_ASSIGNED,
    FOLLOW_UP_DUE,
    FOLLOW_UP_OVERDUE,
    INVOICE_CREATED,
    INVOICE_OVERDUE,
    PAYMENT_RECEIVED,
    PAYMENT_PARTIAL,
    INVOICE_FULLY_PAID,
    CUSTOMER_CREATED,
    ENQUIRY_CONVERTED,
    LOGIN_FAILED,
    LOGIN_RATE_LIMITED
}
